name: Python Application Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build Executable
      run: |
        ls
        pyinstaller -F -n=sample .\main.py
        ls

    - name: Archive Executable and Keys
      run: |
        Compress-Archive -Path dist\sample.exe -DestinationPath release.zip

    - name: Tag Info
      id: update_tag_range
      run: |
          # 현재 커밋된 태그 정보를 가져옵니다.
          $CURRENT_TAG = git describe --tags --abbrev=0
          echo "CURRENT_TAG=$CURRENT_TAG" | Out-File -Append -FilePath $env:GITHUB_ENV
          # 현재 커밋된 태그를 제외한 이전 태그를 가져옵니다.
          $PREVIOUS_TAG = git describe --tags --abbrev=0 "$CURRENT_TAG"^
          echo "PREVIOUS_TAG=$PREVIOUS_TAG" | Out-File -Append -FilePath $env:GITHUB_ENV          
          # 이전 태그 부터 변경된 항목들을 모두 조회합니다.
          $CHANGED_REVISIONS = git log "$PREVIOUS_TAG.." --pretty=format:"[%h] %s"
          echo "CHANGED_REVISIONS=$CHANGED_REVISIONS" | Out-File -Append -FilePath $env:GITHUB_ENV

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: ${{ env.CHANGED_REVISIONS }}
        draft: false
        prerelease: false
    
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release.zip
        asset_name: release.zip
        asset_content_type: application/zip
