name: Python Application Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build Executable
      run: |
        ls
        pyinstaller -F -n=sample .\main.py
        ls

    - name: Archive Executable and Keys
      run: |
        Compress-Archive -Path dist\sample.exe -DestinationPath release.zip

    - name: Get Current Tag
      id: current_tag
      run: |
        CURRENT_TAG=$(git describe --tags --abbrev=0)
        echo "Current Tag: $CURRENT_TAG"
        echo "CURRENT_TAG=$CURRENT_TAG" >> $GITHUB_ENV

    - name: Get Previous Tag
      id: previous_tag
      run: |
        PREVIOUS_TAG=$(git describe --tags --abbrev=0 $(git rev-list --tags --skip=1 --max-count=1))
        echo "Previous Tag: $PREVIOUS_TAG"
        echo "PREVIOUS_TAG=$PREVIOUS_TAG" >> $GITHUB_ENV

    - name: Print Tag
      id: print_tag
      run: |
        echo "Current Tag: $CURRENT_TAG"
        echo "Previous Tag: $PREVIOUS_TAG"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: ${{ env.TAG_MESSAGE }}
        draft: false
        prerelease: false
    
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release.zip
        asset_name: release.zip
        asset_content_type: application/zip
